project:
  type: website
  output-dir: docs
  render:
    - TUTORIAL.qmd

website:
  title: "Bodge tutorial"
  navbar:
    left:
      - href: https://github.com/jabirali/bodge
        text: GitHub
      - href: https://pypi.org/project/bodge/
        text: PyPI

format:
  html:
    theme: journal
    toc: true

execute: 
  cache: true

jupyter: python3
