name: bodge
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - beartype
  - black
  - h5py
  - isort
  - matplotlib
  - numpy
  - pytest
  - rich
  - scipy
  - seaborn
  - tqdm
  - pip:
    - prefetch_generator